name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t my-flask-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push my-flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    
    needs: build

  steps:
    - name: Deploy to Render
      run: |
        curl -sL https://render.com/install.sh | bash
        
        render login --email bvvkarthik1155@gmail.com --password Karthik@1155
        
        render --yaml=render.yaml