name: Deploy to Render

on:
  push:
    branches:
      - main  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bvvkarthik1155/crsystem:latest  
    
    - name: Deploy to Render
      uses: renderapp/render-action@1.0.2
      with:
        render_token: ${{ secrets.RENDER_TOKEN }}
        dockerfile: Dockerfile
        image: bvvkarthik1155/crsystem:latest  
