name: Deploy to Render

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t myapp:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret
      
    - name: Push Docker image to Docker Hub
      run: |
        docker tag myapp:latest $DOCKER_USERNAME/myapp:latest
        docker push $DOCKER_USERNAME/myapp:latest
        
    - name: Set up Render CLI
      uses: renderhq/action-setup-render-cli@v1
      
    - name: Deploy to Render
      run: |
        render deploy --config render.yaml
