name: Deploy to Render

on:
  push:
    branches:
      - main  # or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Download Render CLI
        run: |
          wget https://github.com/render-oss/render-cli/releases/download/v0.1.11/render-linux-x86_64 -O render
          chmod +x render
        
      
      - name: Install Render CLI
        run: |
          sudo mv render /usr/local/bin/render
        
      - name: Configure Render
        run: render config --profile bvvkarthik1155@gmail.com --verbose Karthik@1155
      
      - name: Deploy to Render
        run: render up --name crsystem --docker-image bvvkarthik1155/crsystem:latest  # Change this to your app and Docker image name
