name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Render
      uses: renderhq/github-action@1.3.0
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        dockerfile: Dockerfile
        context: .  # Path to the directory containing Dockerfile
        env: python  # Environment type
        startCommand: gunicorn -b :8080 app:app  # Adjust start command if needed
        plan: starter
