name: Deploy to Render

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t dockerfile -f Dockerfile .
      
    - name: Install Render CLI
      run: |
        curl -sL https://install.render.com/agent.sh | sh

    - name: Login to Render
      run: |
        render login --email bvvkarthik1155@gmail.com --password Karthik@1155
        
    - name: Push Docker image to Render
      run: |
        docker tag your-repository-name registry.render.com/CRSystem
        
    - name: Deploy to Render
      run: render deploy --image registry.render.com/CRSystem:latest --force
