name: Deploy to Render

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bvvkarthik1155/crsystem:latest  
    
    - name: Install Render CLI
      run: |
        curl -O https://render.com/static/cli/rendertool_latest_linux_amd64.tar.gz
        tar -zxvf rendertool_latest_linux_amd64.tar.gz
        sudo mv rendertool /usr/local/bin/render
        
    - name: Configure Render
      run: render login --token ${{ secrets.RENDER_TOKEN }}
      
    - name: Deploy to Render
      run: render up --name crsystem --docker-image bvvkarthik1155/crsystem:latest  # Change this to your app and Docker image name
